DROP TABLE SMT_USER;

CREATE TABLE ADMIN
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 FIRST_NAME VARCHAR(64) NOT NULL,
 MIDDLE_NAME VARCHAR(64),
 LAST_NAME VARCHAR(64) NOT NULL,
 PHONE VARCHAR(16),
 USERNAME VARCHAR(64) NOT NULL,
 PASSWORD VARCHAR(16) NOT NULL,
 EMAIL VARCHAR(64),
 ADDRESS VARCHAR(64),
 STATUS VARCHAR(64)NOT NULL,
 SESSION VARCHAR(64),
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 ADMINROLE VARCHAR(64)
);
insert into SMT_LOCAL.ADMIN (FIRST_NAME,LAST_NAME,USERNAME,PASSWORD,STATUS) values('global-admin','global-admin','global-admin','manager','ACTIVE');

