CREATE TABLE PAYMENT
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 STUDENT_ID INTEGER(14) NOT NULL,
 NAME VARCHAR(64) NOT NULL,
 PAYMENT_AMOUNT INTEGER(14) NOT NULL,
 PAYMENT_DISCOUNT INTEGER(14),
 SPLIT_NUMBER INTEGER(14) NOT NULL,
 PAYED_AMOUNT INTEGER(14),
 START_DATE DATE NOT NULL,
 END_DATE DATE NOT NULL,
 DESCRIPTION VARCHAR(1024),
 PAYMENT_STATUS VARCHAR(64),
 STATUS VARCHAR(64),
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);
