
CREATE TABLE STUDENT
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 FIRST_NAME VARCHAR(64) NOT NULL,
 MIDDLE_NAME VARCHAR(64),
 LAST_NAME VARCHAR(64) NOT NULL,
 PHONE VARCHAR(16),
 USERNAME VARCHAR(64) NOT NULL,
 PASSWORD VARCHAR(16) NOT NULL,
 EMAIL VARCHAR(64),
 ADDRESS VARCHAR(64),
 DESCRIPTION VARCHAR(1024),
 DOB DATE,
 STATUS VARCHAR(64)NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date
);


