
CREATE TABLE YEAR
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(64) NOT NULL,
 START_DATE DATE NOT NULL,
 END_DATE DATE NOT NULL,
 DESCRIPTION VARCHAR(1024),
 YEAR_STATUS VARCHAR(64)NOT NULL,
 STATUS VARCHAR(64)NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date
);


