CREATE TABLE SMT_USER
(ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 FIRST_NAME VARCHAR(64) NOT NULL,
 MIDDLE_NAME VARCHAR(64) NOT NULL,
 LAST_NAME VARCHAR(64) NOT NULL,
 PHONE INT(16) NOT NULL,
 USERNAME VARCHAR(64) NOT NULL,
 PASSWORD VARCHAR(16) NOT NULL,
 EMAIL VARCHAR(64),
 ADDRESS VARCHAR(64)NOT NULL,
 ROLE VARCHAR(64)NOT NULL 
)