CREATE DATABASE MY_BACK_END;

CREATE TABLE PROJECT
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(64) NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 CONSTRAINT UK_PROJECT_NAME UNIQUE (NAME)
);

CREATE TABLE PROJECT_ENTITY
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(64) NOT NULL,
 PROJECT_ID BIGINT NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 CONSTRAINT UK_PROJECT_ENTITY_NAME UNIQUE (NAME),
 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE ATTRIBUTE
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(64) NOT NULL,
 ENTITY_ID BIGINT NOT NULL,
 ENTITY_TYPE VARCHAR(64) NOT NULL,
 IS_MANDATORY BOOL NOT NULL,
 IS_UNIQUE BOOL NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 REF_PROJECT_NAME VARCHAR(64),
 FOREIGN KEY (ENTITY_ID) REFERENCES PROJECT_ENTITY(ID) 
);

