CREATE DATABASE MY_BACK_END;

CREATE TABLE PROJECT
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(64) NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 CONSTRAINT UK_PROJECT_NAME UNIQUE (NAME)
);

CREATE TABLE PROJECT_ENTITY
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(64) NOT NULL,
 PROJECT_ID BIGINT NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 CONSTRAINT UK_PROJECT_ENTITY_NAME UNIQUE (NAME),
 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID)
);

CREATE TABLE ATTRIBUTE
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(64) NOT NULL,
 ENTITY_ID BIGINT NOT NULL,
 ENTITY_TYPE VARCHAR(64) NOT NULL,
 IS_MANDATORY BOOL NOT NULL,
 IS_UNIQUE BOOL NOT NULL,
 CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
 ENUM_VALUES VARCHAR(1000),
 FOREIGN KEY (ENTITY_ID) REFERENCES PROJECT_ENTITY(ID) 
);

CREATE TABLE ENTITY_RELATION
(
 ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR (255 ) NOT NULL,
   ENTITY_1   BIGINT NOT NULL,
   ENTITY_1_TYPE      VARCHAR (255 ) NOT NULL,
   ENTITY_2   BIGINT NOT NULL,
   ENTITY_2_TYPE      VARCHAR (255 ) NOT NULL,
    CREATEDBY VARCHAR(64),
 UPDATEDBY VARCHAR(64),
 CREATEDATE date,
 UPDATEDATE date,
   CONSTRAINT ENTITY_RELATION_PK PRIMARY KEY (ID),
   CONSTRAINT FK_ENTITY1 FOREIGN KEY (ENTITY_1) REFERENCES PROJECT_ENTITY (ID) ON DELETE CASCADE,
   CONSTRAINT FK_ENTITY2 FOREIGN KEY (ENTITY_2) REFERENCES PROJECT_ENTITY (ID) ON DELETE CASCADE
);

